//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicareEnrollmentAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HME_HumanaPlans
    {
        public int PlanKey { get; set; }
        public string PlanYear { get; set; }
        public string ContractNumber { get; set; }
        public string PBPNo { get; set; }
        public string Counties { get; set; }
        public string PlanName { get; set; }
        public string PlanId { get; set; }
        public string CompFormNumber { get; set; }
        public string LedgerNo { get; set; }
    }
}
